apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave1
  namespace: devops
  labels:
    app: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      serviceAccountName: jenkins-admin
      automountServiceAccountToken: true
      containers:
      - name: slave
        image: sabrin9696/final:slave
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock

