---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: devops
spec:
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer